# Generated by Django 2.2.7 on 2020-02-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0008_auto_20200213_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='titre',
            field=models.CharField(max_length=70),
        ),
    ]
