# Generated by Django 2.2.7 on 2020-02-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0009_auto_20200213_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('etat', models.CharField(choices=[('1', 'refusee'), ('2', 'acceptee')], default=('2', 'acceptee'), max_length=10)),
                ('type', models.CharField(choices=[('1', 'incident'), ('2', 'modification')], default=('2', 'modification'), max_length=10)),
                ('created_by', models.CharField(max_length=80)),
                ('assigned_to', models.CharField(max_length=80)),
            ],
        ),
    ]
