# Generated by Django 2.2.7 on 2020-02-17 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0011_ticket_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todoapi.Task'),
        ),
    ]
