# Generated by Django 2.2.7 on 2020-02-17 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0012_auto_20200217_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Task',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='todoapi.Task'),
            preserve_default=False,
        ),
    ]
