# Generated by Django 2.2.7 on 2020-02-17 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0014_auto_20200217_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todoapi.Task'),
        ),
    ]
