# Generated by Django 2.2.7 on 2020-02-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0015_auto_20200217_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='img',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='etat',
            field=models.CharField(choices=[('1', 'refusee'), ('2', 'acceptee')], default=('2', 'acceptee'), max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
