# Generated by Django 2.2.7 on 2020-02-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0016_auto_20200217_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('created_by', models.CharField(max_length=80)),
                ('assigned_to', models.CharField(max_length=80)),
                ('img', models.ImageField(upload_to='note')),
            ],
        ),
    ]
