# Generated by Django 2.2.7 on 2020-02-20 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0021_auto_20200218_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='desc',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='note',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='Task',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='type',
        ),
        migrations.AddField(
            model_name='task',
            name='ticket',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='todoapi.Ticket'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='etat',
            field=models.CharField(choices=[('1', 'incident'), ('2', 'modification')], default=('2', 'modification'), max_length=10),
        ),
        migrations.DeleteModel(
            name='note',
        ),
        migrations.DeleteModel(
            name='piece',
        ),
    ]
