# Generated by Django 2.2.7 on 2020-02-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0023_note_piece'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
