# Generated by Django 2.2.7 on 2020-03-06 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0025_auto_20200226_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='assigned_to',
            new_name='assigned_too',
        ),
    ]
