# Generated by Django 2.2.7 on 2020-03-06 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0026_auto_20200306_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='assigned_too',
            new_name='assigned_to',
        ),
    ]
