# Generated by Django 2.2.7 on 2020-03-08 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0027_auto_20200306_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_to',
        ),
    ]
