# Generated by Django 2.2.7 on 2020-03-10 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0028_remove_ticket_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='etablissement',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='todoapi.Etablissement'),
            preserve_default=False,
        ),
    ]
