# Generated by Django 2.2.7 on 2020-03-10 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0030_auto_20200310_1518'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Etablissement',
            new_name='Etablissements',
        ),
    ]
