# Generated by Django 2.2.7 on 2020-03-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0033_remove_ticket_etablissement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Etablissements',
        ),
    ]
