# Generated by Django 2.2.7 on 2020-03-13 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0036_auto_20200310_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='etablissement',
        ),
        migrations.DeleteModel(
            name='Etablissements',
        ),
    ]
