# Generated by Django 2.2.7 on 2020-04-30 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0037_auto_20200313_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='Task',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='todoapi.Task'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='titre',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
